services:
  db:
    image: postgres:16
    env_file:
        - .env
    ports:
      - "5432:5432"
    volumes:
      - nito-db:/var/lib/postgresql/data
  broker:
    image: nito-broker:latest
    network_mode: host
    volumes:
      - ./broker/config.yml:/app/broker/config.yml:ro
    depends_on:
      - db

volumes:
  nito-db: